version: '3.9'
services:
  pfmdb:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        http_proxy: ${HTTP_PROXY}
    image: local/pfmdb
    container_name: pfmdb
    volumes:
      - ./pfmdb:/app
    command: /start-reload.sh
    environment:
      MAX_WORKERS: 1
      SESSION_USERNAME: localuser
      MD_SESSIONUSER: localuser
      MD_URI: mongodb://mongo-alias:27017
      MD_USERNAME: admin
      MD_PASSWORD: admin
      LOGGING: CONSOLE
    ports:
      - "8055:8055"
      - "8025:8025"
      - "6900:6900"
    networks:
      - local
      - mongo_net
  mongo:
    image: mongo:latest
    container_name: pfmongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    security_opt:
      - seccomp:unconfined
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      mongo_net:
        aliases:
          - mongo-alias
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
  mongo-express:
    image: mongo-express:latest
    container_name: pfmongo-db-ui
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo-alias
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - mongo_net
    depends_on:
      - mongo
    restart: unless-stopped
networks:
  mongo_net:
    name: pfmongo_mongo
  local:
volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG

